//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyCard.WebFront.API.Models
{
	// Mixin content Type 1084 with alias "contactUs"
	/// <summary>Contact Us</summary>
	public partial interface IContactUs : IPublishedContent
	{
		/// <summary>Customer Support</summary>
		IHtmlString CustomerSupport { get; }

		/// <summary>Customer Support Title</summary>
		string CustomerSupportTitle { get; }

		/// <summary>Facebook link</summary>
		string FacebookLink { get; }

		/// <summary>Investor Relation</summary>
		IHtmlString InvestorRelation { get; }

		/// <summary>Heading</summary>
		string SocialMediaHeading { get; }

		/// <summary>Technical Support</summary>
		IHtmlString TechnicalSupport { get; }
	}

	/// <summary>Contact Us</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : PublishedContentModel, IContactUs
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Customer Support
		///</summary>
		[ImplementPropertyType("customerSupport")]
		public IHtmlString CustomerSupport
		{
			get { return GetCustomerSupport(this); }
		}

		/// <summary>Static getter for Customer Support</summary>
		public static IHtmlString GetCustomerSupport(IContactUs that) { return that.GetPropertyValue<IHtmlString>("customerSupport"); }

		///<summary>
		/// Customer Support Title
		///</summary>
		[ImplementPropertyType("customerSupportTitle")]
		public string CustomerSupportTitle
		{
			get { return GetCustomerSupportTitle(this); }
		}

		/// <summary>Static getter for Customer Support Title</summary>
		public static string GetCustomerSupportTitle(IContactUs that) { return that.GetPropertyValue<string>("customerSupportTitle"); }

		///<summary>
		/// Facebook link
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public string FacebookLink
		{
			get { return GetFacebookLink(this); }
		}

		/// <summary>Static getter for Facebook link</summary>
		public static string GetFacebookLink(IContactUs that) { return that.GetPropertyValue<string>("facebookLink"); }

		///<summary>
		/// Investor Relation
		///</summary>
		[ImplementPropertyType("investorRelation")]
		public IHtmlString InvestorRelation
		{
			get { return GetInvestorRelation(this); }
		}

		/// <summary>Static getter for Investor Relation</summary>
		public static IHtmlString GetInvestorRelation(IContactUs that) { return that.GetPropertyValue<IHtmlString>("investorRelation"); }

		///<summary>
		/// Heading
		///</summary>
		[ImplementPropertyType("socialMediaHeading")]
		public string SocialMediaHeading
		{
			get { return GetSocialMediaHeading(this); }
		}

		/// <summary>Static getter for Heading</summary>
		public static string GetSocialMediaHeading(IContactUs that) { return that.GetPropertyValue<string>("socialMediaHeading"); }

		///<summary>
		/// Technical Support
		///</summary>
		[ImplementPropertyType("technicalSupport")]
		public IHtmlString TechnicalSupport
		{
			get { return GetTechnicalSupport(this); }
		}

		/// <summary>Static getter for Technical Support</summary>
		public static IHtmlString GetTechnicalSupport(IContactUs that) { return that.GetPropertyValue<IHtmlString>("technicalSupport"); }
	}
}
