//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyCard.WebFront.API.Models
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IContactUs, ISEO, ISettings
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("banner")]
		public IEnumerable<IPublishedContent> Banner
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("banner"); }
		}

		///<summary>
		/// Cool Main Heading
		///</summary>
		[ImplementPropertyType("coolMainHeading")]
		public IHtmlString CoolMainHeading
		{
			get { return this.GetPropertyValue<IHtmlString>("coolMainHeading"); }
		}

		///<summary>
		/// Cool Sections
		///</summary>
		[ImplementPropertyType("coolSections")]
		public IEnumerable<IPublishedContent> CoolSections
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("coolSections"); }
		}

		///<summary>
		/// Green Image
		///</summary>
		[ImplementPropertyType("greenImage")]
		public IPublishedContent GreenImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("greenImage"); }
		}

		///<summary>
		/// Green Text
		///</summary>
		[ImplementPropertyType("greenText")]
		public IHtmlString GreenText
		{
			get { return this.GetPropertyValue<IHtmlString>("greenText"); }
		}

		///<summary>
		/// Why Description
		///</summary>
		[ImplementPropertyType("whyDescription")]
		public IHtmlString WhyDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("whyDescription"); }
		}

		///<summary>
		/// why Image
		///</summary>
		[ImplementPropertyType("whyImage")]
		public IPublishedContent WhyImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("whyImage"); }
		}

		///<summary>
		/// Why Title Text
		///</summary>
		[ImplementPropertyType("whyTitleText")]
		public IHtmlString WhyTitleText
		{
			get { return this.GetPropertyValue<IHtmlString>("whyTitleText"); }
		}

		///<summary>
		/// Customer Support
		///</summary>
		[ImplementPropertyType("customerSupport")]
		public IHtmlString CustomerSupport
		{
			get { return MyCard.WebFront.API.Models.ContactUs.GetCustomerSupport(this); }
		}

		///<summary>
		/// Customer Support Title
		///</summary>
		[ImplementPropertyType("customerSupportTitle")]
		public string CustomerSupportTitle
		{
			get { return MyCard.WebFront.API.Models.ContactUs.GetCustomerSupportTitle(this); }
		}

		///<summary>
		/// Facebook link
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public string FacebookLink
		{
			get { return MyCard.WebFront.API.Models.ContactUs.GetFacebookLink(this); }
		}

		///<summary>
		/// Investor Relation
		///</summary>
		[ImplementPropertyType("investorRelation")]
		public IHtmlString InvestorRelation
		{
			get { return MyCard.WebFront.API.Models.ContactUs.GetInvestorRelation(this); }
		}

		///<summary>
		/// Heading
		///</summary>
		[ImplementPropertyType("socialMediaHeading")]
		public string SocialMediaHeading
		{
			get { return MyCard.WebFront.API.Models.ContactUs.GetSocialMediaHeading(this); }
		}

		///<summary>
		/// Technical Support
		///</summary>
		[ImplementPropertyType("technicalSupport")]
		public IHtmlString TechnicalSupport
		{
			get { return MyCard.WebFront.API.Models.ContactUs.GetTechnicalSupport(this); }
		}

		///<summary>
		/// Meta Description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return MyCard.WebFront.API.Models.SEO.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta Keywords
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords
		{
			get { return MyCard.WebFront.API.Models.SEO.GetMetaKeywords(this); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return MyCard.WebFront.API.Models.SEO.GetPageTitle(this); }
		}

		///<summary>
		/// Company Logo
		///</summary>
		[ImplementPropertyType("companyLogo")]
		public IPublishedContent CompanyLogo
		{
			get { return MyCard.WebFront.API.Models.Settings.GetCompanyLogo(this); }
		}
	}
}
