//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyCard.WebFront.API.Models
{
	/// <summary>Home Cool Section</summary>
	[PublishedContentModel("homeCoolSection")]
	public partial class HomeCoolSection : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homeCoolSection";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomeCoolSection(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomeCoolSection, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cool Description
		///</summary>
		[ImplementPropertyType("coolDescription")]
		public IHtmlString CoolDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("coolDescription"); }
		}

		///<summary>
		/// Cool Heading
		///</summary>
		[ImplementPropertyType("coolHeading")]
		public IHtmlString CoolHeading
		{
			get { return this.GetPropertyValue<IHtmlString>("coolHeading"); }
		}

		///<summary>
		/// cool Image
		///</summary>
		[ImplementPropertyType("coolImage")]
		public IPublishedContent CoolImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("coolImage"); }
		}
	}
}
