//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyCard.WebFront.API.Models
{
	/// <summary>Product</summary>
	[PublishedContentModel("product")]
	public partial class Product : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "product";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Product(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Product, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Features
		///</summary>
		[ImplementPropertyType("features")]
		public IEnumerable<IPublishedContent> Features
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("features"); }
		}

		///<summary>
		/// Features Heading
		///</summary>
		[ImplementPropertyType("featuresHeading")]
		public string FeaturesHeading
		{
			get { return this.GetPropertyValue<string>("featuresHeading"); }
		}

		///<summary>
		/// My Card Benefits
		///</summary>
		[ImplementPropertyType("myCardBenefits")]
		public IEnumerable<IPublishedContent> MyCardBenefits
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("myCardBenefits"); }
		}

		///<summary>
		/// My Card Benefits Heading
		///</summary>
		[ImplementPropertyType("myCardBenefitsHeading")]
		public string MyCardBenefitsHeading
		{
			get { return this.GetPropertyValue<string>("myCardBenefitsHeading"); }
		}

		///<summary>
		/// Product Banner Image
		///</summary>
		[ImplementPropertyType("productBannerImage")]
		public IPublishedContent ProductBannerImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("productBannerImage"); }
		}

		///<summary>
		/// Product Banner Image Text
		///</summary>
		[ImplementPropertyType("productBannerImageText")]
		public string ProductBannerImageText
		{
			get { return this.GetPropertyValue<string>("productBannerImageText"); }
		}
	}
}
