//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MyCard.WebFront.API.Models
{
	// Mixin content Type 1086 with alias "settings"
	/// <summary>Settings</summary>
	public partial interface ISettings : IPublishedContent
	{
		/// <summary>Company Logo</summary>
		IPublishedContent CompanyLogo { get; }
	}

	/// <summary>Settings</summary>
	[PublishedContentModel("settings")]
	public partial class Settings : PublishedContentModel, ISettings
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "settings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Settings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Settings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Company Logo
		///</summary>
		[ImplementPropertyType("companyLogo")]
		public IPublishedContent CompanyLogo
		{
			get { return GetCompanyLogo(this); }
		}

		/// <summary>Static getter for Company Logo</summary>
		public static IPublishedContent GetCompanyLogo(ISettings that) { return that.GetPropertyValue<IPublishedContent>("companyLogo"); }
	}
}
