//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCard.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaptionsAll {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaptionsAll() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCard.Web.Resources.CaptionsAll", typeof(CaptionsAll).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly click on the link sent to your email at the time of registration or click.
        /// </summary>
        public static string AcivationLinkMessage1 {
            get {
                return ResourceManager.GetString("AcivationLinkMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to resend the link.
        /// </summary>
        public static string AcivationLinkMessage2 {
            get {
                return ResourceManager.GetString("AcivationLinkMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ActivateLicenseButton {
            get {
                return ResourceManager.GetString("ActivateLicenseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate License.
        /// </summary>
        public static string ActivateLicenseTitle {
            get {
                return ResourceManager.GetString("ActivateLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string ActivationLinkMessageHere {
            get {
                return ResourceManager.GetString("ActivationLinkMessageHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        public static string AdminLoginTitle {
            get {
                return ResourceManager.GetString("AdminLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BillingAddressButton {
            get {
                return ResourceManager.GetString("BillingAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddressCaption {
            get {
                return ResourceManager.GetString("BillingAddressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddressTitle {
            get {
                return ResourceManager.GetString("BillingAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login using your corporate office 365 account.
        /// </summary>
        public static string BusinessEmailIdLogin {
            get {
                return ResourceManager.GetString("BusinessEmailIdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Title.
        /// </summary>
        public static string BusinessTitle {
            get {
                return ResourceManager.GetString("BusinessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to change description?.
        /// </summary>
        public static string ChangeDescriptionConfirmation {
            get {
                return ResourceManager.GetString("ChangeDescriptionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password been changed successfully..
        /// </summary>
        public static string ChangePasswordThanksMessage {
            get {
                return ResourceManager.GetString("ChangePasswordThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to change price?.
        /// </summary>
        public static string ChangePriceConfirmation {
            get {
                return ResourceManager.GetString("ChangePriceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Detail have been updated..
        /// </summary>
        public static string CompanyDetailsUpdated {
            get {
                return ResourceManager.GetString("CompanyDetailsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CompanyEditCancelButton {
            get {
                return ResourceManager.GetString("CompanyEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Listing.
        /// </summary>
        public static string CompanyListingTitle {
            get {
                return ResourceManager.GetString("CompanyListingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo.
        /// </summary>
        public static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Business Legal Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePasswordButton {
            get {
                return ResourceManager.GetString("CreatePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already created your password or link is expired..
        /// </summary>
        public static string CreatePasswordExitMessage {
            get {
                return ResourceManager.GetString("CreatePasswordExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created your password, you can &lt;a href=&quot;@Url.Action(&quot;Login&quot;, &quot;Registration&quot;)&quot; class=&quot;txt-bold color-blue&quot;&gt;Login&lt;/a&gt; to your account..
        /// </summary>
        public static string CreatePasswordThanksMessage {
            get {
                return ResourceManager.GetString("CreatePasswordThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks .
        /// </summary>
        public static string CreatePasswordThanksTitle {
            get {
                return ResourceManager.GetString("CreatePasswordThanksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string CreatePasswordTitle {
            get {
                return ResourceManager.GetString("CreatePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string CurrencyInitial {
            get {
                return ResourceManager.GetString("CurrencyInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the status of employee?.
        /// </summary>
        public static string DeActivateEmployeeAdminMessage1 {
            get {
                return ResourceManager.GetString("DeActivateEmployeeAdminMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to deactivate the employee license?.
        /// </summary>
        public static string DeActivateEmployeeMessage1 {
            get {
                return ResourceManager.GetString("DeActivateEmployeeMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that this action cannot be undone.
        /// </summary>
        public static string DeActivateEmployeeMessage2 {
            get {
                return ResourceManager.GetString("DeActivateEmployeeMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name (Integrated with Microsoft Office 365 Services).
        /// </summary>
        public static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string EditCompany {
            get {
                return ResourceManager.GetString("EditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to change password, .
        /// </summary>
        public static string EditCompanyChangePassword {
            get {
                return ResourceManager.GetString("EditCompanyChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string EditCompanyChangePasswordClick {
            get {
                return ResourceManager.GetString("EditCompanyChangePasswordClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please find the below link for password reset.&lt;br /&gt; {0}/Admin/Default/ResetPassword/?param={1} &lt;br/&gt; Regards&lt;br /&gt; MyCard.Com.
        /// </summary>
        public static string EmailBodyAdminResetPassword {
            get {
                return ResourceManager.GetString("EmailBodyAdminResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyCard - Create Your Password.
        /// </summary>
        public static string EmailPasswordCreationSubject {
            get {
                return ResourceManager.GetString("EmailPasswordCreationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to myCards™.
        /// </summary>
        public static string EmailPasswordCreationSubjectMSO {
            get {
                return ResourceManager.GetString("EmailPasswordCreationSubjectMSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}, &lt;br/&gt; &lt;br/&gt;
        ///
        ///We were told you forgot your password and we’re here to assist! &lt;br/&gt; &lt;br/&gt;
        ///
        ///Use the following link to reset your password and gain access to myCards. &lt;br/&gt; &lt;br/&gt;
        ///
        ///&lt;a href=&quot;{1}/CompanyDashboard/ResetPassword/?param={2}&quot;&gt;{1}/CompanyDashboard/ResetPassword/?param={2}&lt;/a&gt; &lt;br/&gt; &lt;br/&gt;
        ///
        ///
        ///Regards, &lt;br/&gt; &lt;br/&gt;
        ///
        ///myCards Team
        ///.
        /// </summary>
        public static string EmailPasswordResetBody {
            get {
                return ResourceManager.GetString("EmailPasswordResetBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyCard - Password Reset.
        /// </summary>
        public static string EmailPasswordResetSubject {
            get {
                return ResourceManager.GetString("EmailPasswordResetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Listing.
        /// </summary>
        public static string EmployeeListingTitle {
            get {
                return ResourceManager.GetString("EmployeeListingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string ForgotPasswordButton {
            get {
                return ResourceManager.GetString("ForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPasswordLinkOnLogin {
            get {
                return ResourceManager.GetString("ForgotPasswordLinkOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Graph_SendMail_Body_Content {
            get {
                return ResourceManager.GetString("Graph_SendMail_Body_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiries Listing.
        /// </summary>
        public static string InquiryListingTitle {
            get {
                return ResourceManager.GetString("InquiryListingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your interest in myCards™..
        /// </summary>
        public static string InquirySuccessMessage1 {
            get {
                return ResourceManager.GetString("InquirySuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team will get back to you soon..
        /// </summary>
        public static string InquirySuccessMessage2 {
            get {
                return ResourceManager.GetString("InquirySuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain minimum 8 letters (A-z) and numbers (0-9).
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration portal!.
        /// </summary>
        public static string LeftPanelregistrationportal {
            get {
                return ResourceManager.GetString("LeftPanelregistrationportal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your.
        /// </summary>
        public static string LeftPanelWelcome {
            get {
                return ResourceManager.GetString("LeftPanelWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},&lt;br /&gt;&lt;br /&gt;
        ///
        ///You have now successfully completed the myCards Corporate Experience. To begin your myCards User Experience, use the following link(s) to download myCards App.&lt;br /&gt;&lt;br /&gt;
        ///
        ///Android:&lt;br /&gt;
        ///https://googleplay.com/myCardsInc &lt;br /&gt;&lt;br /&gt;
        ///
        ///iOS:&lt;br /&gt;
        ///https://appstore.com/myCardsInc &lt;br /&gt;&lt;br /&gt;
        ///
        /// 
        ///Regards,&lt;br /&gt;&lt;br /&gt;
        ///
        ///myCards Team.
        /// </summary>
        public static string LicenseActivationEmailMessage {
            get {
                return ResourceManager.GetString("LicenseActivationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Activation.
        /// </summary>
        public static string LicenseActivationSubject {
            get {
                return ResourceManager.GetString("LicenseActivationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string LicenseStatus {
            get {
                return ResourceManager.GetString("LicenseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string LoginHere {
            get {
                return ResourceManager.GetString("LoginHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to myCards™? Please.
        /// </summary>
        public static string LoginNewtoMyCards {
            get {
                return ResourceManager.GetString("LoginNewtoMyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string LoginRegister {
            get {
                return ResourceManager.GetString("LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remeber me.
        /// </summary>
        public static string LoginRemeberMe {
            get {
                return ResourceManager.GetString("LoginRemeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Office 365.
        /// </summary>
        public static string LoginSignInMessage {
            get {
                return ResourceManager.GetString("LoginSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myCards™ CMS.
        /// </summary>
        public static string myCardCMS {
            get {
                return ResourceManager.GetString("myCardCMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myCards Designer.
        /// </summary>
        public static string NavBarmyCardsDesigner {
            get {
                return ResourceManager.GetString("NavBarmyCardsDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myPortal.
        /// </summary>
        public static string NavBarmyProfile {
            get {
                return ResourceManager.GetString("NavBarmyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string NavBarPurchase {
            get {
                return ResourceManager.GetString("NavBarPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string NavBarRegister {
            get {
                return ResourceManager.GetString("NavBarRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string NaveBarSignIn {
            get {
                return ResourceManager.GetString("NaveBarSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string NaveBarSignOut {
            get {
                return ResourceManager.GetString("NaveBarSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Licenses.
        /// </summary>
        public static string NoOfLicense {
            get {
                return ResourceManager.GetString("NoOfLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your interest in myCards™..
        /// </summary>
        public static string NotCorporateUserMessage1 {
            get {
                return ResourceManager.GetString("NotCorporateUserMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will shortly receive an email with instructions to proceed..
        /// </summary>
        public static string NotCorporateUserMessage2 {
            get {
                return ResourceManager.GetString("NotCorporateUserMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order File.
        /// </summary>
        public static string OrderFile {
            get {
                return ResourceManager.GetString("OrderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Total.
        /// </summary>
        public static string OrderTotal {
            get {
                return ResourceManager.GetString("OrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasword.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Hello and welcome!&lt;br /&gt;&lt;br /&gt;
        ///
        ///Thank you for your interest in becoming a myCards Enterprise User. To continue with your purchase kindly click on the link below to set your password:&lt;br /&gt;&lt;br /&gt;
        ///
        ///&lt;a href = &apos;{1}/CompanyDashboard/CreatePassword/?param={2} &apos;&gt;{1}/CompanyDashboard/CreatePassword/?param={2}&lt;/a&gt; &lt;br/&gt; &lt;br/&gt; 
        ///
        ///We look forward to having you join myCards and making a Positive Impact!&lt;br /&gt;&lt;br /&gt;
        ///
        ///Best Regards,&lt;br /&gt;&lt;br /&gt;
        ///
        ///myCards Team
        ///.
        /// </summary>
        public static string PasswordCreationEmailBody {
            get {
                return ResourceManager.GetString("PasswordCreationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Hello and welcome!&lt;br /&gt;&lt;br /&gt;
        ///
        ///Thank you for your interest in becoming a myCards Enterprise User. Your account at myCards™ is ready. &lt;br /&gt;&lt;br /&gt;
        ///To continue with the purchase you can login using your existing office 365 credentials, click on the link below to proceed: &lt;br /&gt;&lt;br /&gt;
        ///&lt;a href = &apos;{1}/CompanyDashboard/Login&apos;&gt;{1}/CompanyDashboard/Login&lt;/a&gt; &lt;br/&gt; &lt;br/&gt; 
        ///
        ///We look forward to having you join myCards and making a Positive Impact!&lt;br /&gt;&lt;br /&gt;
        ///
        ///Best Regards,&lt;br /&gt;&lt;br /&gt;
        ///
        ///myCards Team.
        /// </summary>
        public static string PasswordCreationEmailBodyMSO {
            get {
                return ResourceManager.GetString("PasswordCreationEmailBodyMSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string POApprovalButton {
            get {
                return ResourceManager.GetString("POApprovalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Approval.
        /// </summary>
        public static string POApprovalTitle {
            get {
                return ResourceManager.GetString("POApprovalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO CDN.
        /// </summary>
        public static string POCDN {
            get {
                return ResourceManager.GetString("POCDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Date.
        /// </summary>
        public static string PODate {
            get {
                return ResourceManager.GetString("PODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Description.
        /// </summary>
        public static string PODescription {
            get {
                return ResourceManager.GetString("PODescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Listing.
        /// </summary>
        public static string POLIstingTitle {
            get {
                return ResourceManager.GetString("POLIstingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Status.
        /// </summary>
        public static string POStatus {
            get {
                return ResourceManager.GetString("POStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the status of purchase order?.
        /// </summary>
        public static string POStatusChangeMessage {
            get {
                return ResourceManager.GetString("POStatusChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myCard Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business email.
        /// </summary>
        public static string ProfileBusinessEmail {
            get {
                return ResourceManager.GetString("ProfileBusinessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string ProfileCards {
            get {
                return ResourceManager.GetString("ProfileCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards Shared.
        /// </summary>
        public static string ProfileCardsShared {
            get {
                return ResourceManager.GetString("ProfileCardsShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string ProfileCompanies {
            get {
                return ResourceManager.GetString("ProfileCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Accounts Created.
        /// </summary>
        public static string ProfileCompaniesCreated {
            get {
                return ResourceManager.GetString("ProfileCompaniesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string ProfileCompanyName {
            get {
                return ResourceManager.GetString("ProfileCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company website.
        /// </summary>
        public static string ProfileCompanyWebsite {
            get {
                return ResourceManager.GetString("ProfileCompanyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Purchase.
        /// </summary>
        public static string ProfileLastPurchase {
            get {
                return ResourceManager.GetString("ProfileLastPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add licenses.
        /// </summary>
        public static string ProfileLeftPanelAddLicenses {
            get {
                return ResourceManager.GetString("ProfileLeftPanelAddLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myCards Designer.
        /// </summary>
        public static string ProfileLeftPanelmyCardsDesigner {
            get {
                return ResourceManager.GetString("ProfileLeftPanelmyCardsDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myPortal.
        /// </summary>
        public static string ProfileLeftPanelmyProfile {
            get {
                return ResourceManager.GetString("ProfileLeftPanelmyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string ProfileLeftPanelPurchase {
            get {
                return ResourceManager.GetString("ProfileLeftPanelPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Premium.
        /// </summary>
        public static string ProfileLeftPanelUpgradePremium {
            get {
                return ResourceManager.GetString("ProfileLeftPanelUpgradePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses Purchased.
        /// </summary>
        public static string ProfileLicensesPurchased {
            get {
                return ResourceManager.GetString("ProfileLicensesPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since.
        /// </summary>
        public static string ProfileMemberSince {
            get {
                return ResourceManager.GetString("ProfileMemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myCards™ portal.
        /// </summary>
        public static string ProfileMyCard {
            get {
                return ResourceManager.GetString("ProfileMyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile admin.
        /// </summary>
        public static string ProfileProfileAdmin {
            get {
                return ResourceManager.GetString("ProfileProfileAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your.
        /// </summary>
        public static string ProfileWelcome {
            get {
                return ResourceManager.GetString("ProfileWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string PurchaseButtonConfirm {
            get {
                return ResourceManager.GetString("PurchaseButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click calculate for total cost.
        /// </summary>
        public static string PurchaseClickCalculate {
            get {
                return ResourceManager.GetString("PurchaseClickCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click confirm to receive your quotation..
        /// </summary>
        public static string PurchaseClickConfirm {
            get {
                return ResourceManager.GetString("PurchaseClickConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per license USD.
        /// </summary>
        public static string PurchaseCostPerLicense {
            get {
                return ResourceManager.GetString("PurchaseCostPerLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of licenses to calculate total cost..
        /// </summary>
        public static string PurchaseEnterLicenses {
            get {
                return ResourceManager.GetString("PurchaseEnterLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert number of licenses required:.
        /// </summary>
        public static string PurchaseInsertLicense {
            get {
                return ResourceManager.GetString("PurchaseInsertLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase License.
        /// </summary>
        public static string PurchaseLicense {
            get {
                return ResourceManager.GetString("PurchaseLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PurchasePopupButtonNext {
            get {
                return ResourceManager.GetString("PurchasePopupButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your interest in becoming a myCards™ Enterprise User..
        /// </summary>
        public static string PurchaseSuccessMessage1 {
            get {
                return ResourceManager.GetString("PurchaseSuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will shortly receive the product proposal to your registered email. .
        /// </summary>
        public static string PurchaseSuccessMessage2 {
            get {
                return ResourceManager.GetString("PurchaseSuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly click next to proceed with your purchase..
        /// </summary>
        public static string PurchaseSuccessMessage3 {
            get {
                return ResourceManager.GetString("PurchaseSuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your interest..
        /// </summary>
        public static string PurchaseThanksMessage {
            get {
                return ResourceManager.GetString("PurchaseThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string PurchaseThanksTitle {
            get {
                return ResourceManager.GetString("PurchaseThanksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string PurchaseTotalCost {
            get {
                return ResourceManager.GetString("PurchaseTotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for uploading your purchase order..
        /// </summary>
        public static string PurchaseUploadPOSuccessMessage1 {
            get {
                return ResourceManager.GetString("PurchaseUploadPOSuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will shortly receive an email with instructions to proceed..
        /// </summary>
        public static string PurchaseUploadPOSuccessMessage2 {
            get {
                return ResourceManager.GetString("PurchaseUploadPOSuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},&lt;br/&gt;&lt;br/&gt;
        ///
        ///We are thrilled to know that you are one step closer to becoming a myCards Enterprise Partner.&lt;br/&gt;&lt;br/&gt;
        ///
        ///Attached, herewith, is your myCards proposal which includes details on:&lt;br/&gt;&lt;br/&gt;
        ///
        ///1)	Benefits and Features&lt;br/&gt;
        ///2)	Licensing Structure&lt;br/&gt;
        ///3)	CSR Impact&lt;br/&gt;
        ///4)	Quotation&lt;br/&gt;
        ///5)	Terms &amp; Conditions&lt;br/&gt;
        ///
        ///Should you have any queries, please do not hesitate to contact us at sales@mycards.com&lt;br/&gt;&lt;br/&gt;
        ///
        ///We look forward to having you onboard our myCards journey towards  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QoutationEmailBody {
            get {
                return ResourceManager.GetString("QoutationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyCard.com - Qoutation.
        /// </summary>
        public static string QoutationEmailSubject {
            get {
                return ResourceManager.GetString("QoutationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;~/img/admin/register-logo.png&apos; /&gt;&lt;br /&gt;&lt;table width=&apos;100%&apos; cellspacing=&apos;0&apos; cellpadding=&apos;2&apos;&gt;
        ///&lt;tr&gt;&lt;td align=&apos;center&apos; style=&apos;background-color: #18B5F0&apos; colspan = &apos;2&apos;&gt;&lt;b&gt;Qoutation&lt;/b&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td colspan = &apos;2&apos;&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;&lt;b&gt;Qoutation No:&lt;/b&gt;{0}&lt;/td&gt;&lt;td&gt;&lt;b&gt;Date: &lt;/b&gt;{1}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td colspan = &apos;2&apos;&gt;&lt;b&gt;Company Name :&lt;/b&gt; {2} &lt;/td&gt;&lt;/tr&gt;
        ///&lt;/table&gt;&lt;br /&gt;
        ///&lt;table border = &apos;1&apos;&gt;&lt;tr&gt;&lt;th&gt;License Type&lt;/th&gt;&lt;th&gt;Number of Licenses&lt;/th&gt;&lt;th&gt;Price Per License&lt;/th&gt;&lt;th&gt;Total Price&lt;/th&gt;
        ///&lt;tr&gt;&lt;td&gt;{6}&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QoutationTemplate {
            get {
                return ResourceManager.GetString("QoutationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the reason for rejection..
        /// </summary>
        public static string ReasonForRejection {
            get {
                return ResourceManager.GetString("ReasonForRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here..
        /// </summary>
        public static string RegisterHere {
            get {
                return ResourceManager.GetString("RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the.
        /// </summary>
        public static string RegisterIacceptthe {
            get {
                return ResourceManager.GetString("RegisterIacceptthe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have already registered, please.
        /// </summary>
        public static string RegisterIfyouAlready {
            get {
                return ResourceManager.GetString("RegisterIfyouAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Office 365 user?.
        /// </summary>
        public static string RegisterNotOfficeUser {
            get {
                return ResourceManager.GetString("RegisterNotOfficeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click.
        /// </summary>
        public static string RegisterNotOfficeUserClick {
            get {
                return ResourceManager.GetString("RegisterNotOfficeUserClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string RegisterNotOfficeUserHere {
            get {
                return ResourceManager.GetString("RegisterNotOfficeUserHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string RegisterSignin {
            get {
                return ResourceManager.GetString("RegisterSignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with Office 365.
        /// </summary>
        public static string RegisterSingupMessage {
            get {
                return ResourceManager.GetString("RegisterSingupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering with myCards™..
        /// </summary>
        public static string RegisterSuccessMessage1 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will shortly receive an email with your login.
        /// </summary>
        public static string RegisterSuccessMessage2 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credentials to continue with your purchase..
        /// </summary>
        public static string RegisterSuccessMessage3 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering with myCards™..
        /// </summary>
        public static string RegisterSuccessMessageCMS1 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessageCMS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you will shortly receive password set up.
        /// </summary>
        public static string RegisterSuccessMessageCMS2 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessageCMS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email to continue with your purchase..
        /// </summary>
        public static string RegisterSuccessMessageCMS3 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessageCMS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for signing up as a Freemium user..
        /// </summary>
        public static string RegisterSuccessMessageFree1 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessageFree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will shortly receive an email with access permission to myCards™ Designer..
        /// </summary>
        public static string RegisterSuccessMessageFree2 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessageFree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering with myCards™..
        /// </summary>
        public static string RegisterSuccessMessageMO1 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessageMO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly click next to continue..
        /// </summary>
        public static string RegisterSuccessMessageMO2 {
            get {
                return ResourceManager.GetString("RegisterSuccessMessageMO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string RegisterTermsOfServices {
            get {
                return ResourceManager.GetString("RegisterTermsOfServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the details to begin registration..
        /// </summary>
        public static string RegistrationFillDetails {
            get {
                return ResourceManager.GetString("RegistrationFillDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you {0} for registrering with us. We have sent you email for creating password..
        /// </summary>
        public static string RegistrationThankyouMessage {
            get {
                return ResourceManager.GetString("RegistrationThankyouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Link.
        /// </summary>
        public static string ResendLinkTitle {
            get {
                return ResourceManager.GetString("ResendLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link has been expired..
        /// </summary>
        public static string ResetPasswordExpiredMessage {
            get {
                return ResourceManager.GetString("ResetPasswordExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        public static string ResetPasswordThanksMessage {
            get {
                return ResourceManager.GetString("ResetPasswordThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Hardcopy.
        /// </summary>
        public static string SendInvoice {
            get {
                return ResourceManager.GetString("SendInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string TermsAccepted {
            get {
                return ResourceManager.GetString("TermsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conidtions.
        /// </summary>
        public static string TermsAndConidtions {
            get {
                return ResourceManager.GetString("TermsAndConidtions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TermsButton {
            get {
                return ResourceManager.GetString("TermsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TermsCaption {
            get {
                return ResourceManager.GetString("TermsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions.
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to licenses have been generated and are ready to use after activation..
        /// </summary>
        public static string TrialLicenseCompletionMessage {
            get {
                return ResourceManager.GetString("TrialLicenseCompletionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial License.
        /// </summary>
        public static string TrialTitle {
            get {
                return ResourceManager.GetString("TrialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the.
        /// </summary>
        public static string UploadPOIacceptThe {
            get {
                return ResourceManager.GetString("UploadPOIacceptThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload PO.
        /// </summary>
        public static string UploadPOLink {
            get {
                return ResourceManager.GetString("UploadPOLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your purchase order (PO) in .pdf format.
        /// </summary>
        public static string UploadPOMainMessage {
            get {
                return ResourceManager.GetString("UploadPOMainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to receive the original hardcopy of the invoice..
        /// </summary>
        public static string UploadPOPopupHardCopy {
            get {
                return ResourceManager.GetString("UploadPOPopupHardCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string UploadPOPopupNext {
            get {
                return ResourceManager.GetString("UploadPOPopupNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Uploaded Successfully.
        /// </summary>
        public static string UploadPoSuccessMessage {
            get {
                return ResourceManager.GetString("UploadPoSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string UploadPOTermofServices {
            get {
                return ResourceManager.GetString("UploadPOTermofServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload PO.
        /// </summary>
        public static string UploadPOTitle {
            get {
                return ResourceManager.GetString("UploadPOTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
